version: '3.8'

services:
  # Neo4j Database
  neo4j:
    image: neo4j:5.25.1
    container_name: rag-neo4j
    ports:
      - "7475:7474"  # Neo4j Browser (DiveTeacher sur port 7475)
      - "7688:7687"  # Bolt protocol (DiveTeacher sur port 7688)
    environment:
      - NEO4J_AUTH=neo4j/${NEO4J_PASSWORD:-change_me_in_production}
      - NEO4J_PLUGINS=["apoc", "graph-data-science"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*,gds.*
    volumes:
      - neo4j-data:/data
      - neo4j-logs:/logs
    healthcheck:
      test: ["CMD", "cypher-shell", "-u", "neo4j", "-p", "${NEO4J_PASSWORD:-change_me_in_production}", "RETURN 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Ollama LLM Server
  ollama:
    image: ollama/ollama:latest
    container_name: rag-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-models:/root/.ollama
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 10s
      timeout: 5s
      retries: 5

  # FastAPI Backend
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: rag-backend
    ports:
      - "8000:8000"
    environment:
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - DEBUG=true
      - CORS_ORIGINS=http://localhost:5173
      - LLM_PROVIDER=${LLM_PROVIDER:-ollama}
      - OLLAMA_BASE_URL=http://ollama:11434
      - OLLAMA_MODEL=${OLLAMA_MODEL:-llama3:8b}
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=${NEO4J_PASSWORD:-change_me_in_production}
      - GRAPHITI_ENABLED=true
      - SENTRY_DSN_BACKEND=${SENTRY_DSN_BACKEND:-}
      - SENTRY_ENVIRONMENT=development
    volumes:
      - uploads:/uploads
    depends_on:
      neo4j:
        condition: service_healthy
      ollama:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  # React Frontend (development)
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile.dev
    container_name: rag-frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8000
      - VITE_SENTRY_DSN=${VITE_SENTRY_DSN:-}
    volumes:
      - ../frontend/src:/app/src
      - ../frontend/public:/app/public
    depends_on:
      - backend

volumes:
  neo4j-data:
  neo4j-logs:
  ollama-models:
  uploads:

